name: Java CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'
        
    - name: Build application
      run: mvn clean compile
      
    - name: Run unit tests
      run: mvn test -Djacoco.skip=true  
      
    - name: Run integration tests  
      run: mvn verify -Djacoco.skip=true
      
    - name: Build JAR
      run: mvn package -DskipTests
      
    - name: Upload JAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: application-jar
        path: target/*.jar

  deploy-demo:
    needs: build-and-test
    runs-on: ubuntu-latest
    
    steps:
    - name: Download JAR
      uses: actions/download-artifact@v4
      with:
        name: application-jar
        
    - name: List files
      run: ls -la
      
    - name: Simulate deployment
      run: |
        echo "🚀 Deploying application..."
        echo "JAR files found:"
        find . -name "*.jar" -type f
        echo "✅ Deployment simulation completed!"
